apiVersion : apps/v1
kind: Deployment
metadata:
  name: prasannaspringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prasannaspringbootapp
  template:
    metadata:
      labels:
        app: prasannaspringbootapp
    spec:
      containers:
        - name: prasannaspringbootapp
          image: saipracticeacr.azurecr.io/akannanspringbootapp
          ports:
          - containerPort: 80