apiVersion: v1
kind: Service
metadata:
    name: prasannaspringbootapp
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      protocol: TCP
      targetPort: 8085
    selector:
        app: prasannaspringbootapp